---
- hostname:
    name: "{{ hostname }}"
  when: hostname is defined
- lineinfile:
    path: /etc/hosts
    regexp: '{{ hostname }}'
    line: 127.0.0.1 {{ hostname }}
  when: hostname is defined

- template:
    src: ./root/_screenrc
    dest: ~/.screenrc

- template:
    src: ./root/_bash_aliases
    dest: ~/.bash_aliases

- lineinfile:
    path: ~/.bashrc
    regexp: 'bash_aliases'
    line: if [ -f ~/.bash_aliases ] ; then . ~/.bash_aliases ; fi

- name: copy ssh key
  ansible.builtin.copy:
    src: "_ssh/{{ ssh_key_name }}"
    dest: "/root/.ssh/{{ ssh_key_name }}"
    owner: root
    group: wheel
    mode: '0600'
