---
- become: true
  apt:
    cache_valid_time: 3600
    update_cache: yes

- apt:
    name:
      - certbot
      - curl
      - git
      - nginx
      - python3-certbot-nginx
      - screen
      - silversearcher-ag
      - tree
      - vim
      - zip
      - openjdk-17-jre ## for jenkins runner
    state: present
  become: true

## amazon in their stupidity cannot play nice with apt
- name: Download AWS CLI
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
- name: Unzip AWS CLI
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true
- name: Install AWS CLI
  command: /tmp/aws/install --update
  args:
    creates: /usr/local/bin/aws


