---
- name: Stop and disable apt-daily timer
  ansible.builtin.systemd:
    name: apt-daily.timer
    enabled: false
    state: stopped
  ignore_errors: true

- name: Stop and disable apt-daily-upgrade timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    enabled: false
    state: stopped
  ignore_errors: true

- name: Stop apt-daily service
  ansible.builtin.systemd:
    name: apt-daily.service
    state: stopped
  ignore_errors: true

- name: Stop apt-daily-upgrade service
  ansible.builtin.systemd:
    name: apt-daily-upgrade.service
    state: stopped
  ignore_errors: true

- name: Disable APT periodic updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "0";
      APT::Periodic::Download-Upgradeable-Packages "0";
      APT::Periodic::AutocleanInterval "0";
      APT::Periodic::Unattended-Upgrade "0";

- name: Disable unattended upgrades package
  ansible.builtin.apt:
    name: unattended-upgrades
    state: absent
    purge: true

