---

- shell: grep -q "127.0.0.1 {{ item }}" /etc/hosts || echo '127.0.0.1 {{ item }}'  >> /etc/hosts
  become: true
  loop: "{{ local_hosts }}"

- shell: grep -q "{{ item.host }} {{ item.domain }}" /etc/hosts || echo '{{ item.host }} {{ item.domain }}'  >> /etc/hosts
  become: true
  loop: "{{ other_hosts }}"

