##
## From: https://wiki.debian.org/WireGuard
##
---
- lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#\s*net.ipv4.ip_forward.*$'
    line: net.ipv4.ip_forward=1

- shell: sysctl -p

- set_fact:
    all_wg_peers: >-
      {{
        groups['all']
        | map('extract', hostvars, 'wg_config')
        | list
      }}
  # run_once: true
- name: debug all_wg_peers
  debug:
    var: all_wg_peers

- name: wg0.conf
  template:
    src: etc/wireguard/wg0.conf-server
    dest: /etc/wireguard/wg0.conf

# - name: start wg-quick
#   shell: systemctl start wg-quick@wg0

- name: show wg0
  shell: ip a show wg0


