---

## amazon in their stupidity cannot play nice with apt
- name: Download AWS CLI
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
- name: Unzip AWS CLI
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true
- name: Install AWS CLI
  command: /tmp/aws/install --update
  args:
    creates: /usr/local/bin/aws

- name: Create .aws directory
  file:
    path: "{{ aws_home }}/.aws"
    state: directory
    owner: "{{ aws_user }}"
    group: "{{ aws_group }}"
    mode: "0700"

- name: Install credentials
  template:
    src: root/_aws/credentials
    dest: "{{ aws_home }}/.aws/credentials"
    owner: "{{ aws_user }}"
    group: "{{ aws_group }}"
    mode: "0600"

- name: Install config
  template:
    src: root/_aws/config
    dest: "{{ aws_home }}/.aws/config"
    owner: "{{ aws_user }}"
    group: "{{ aws_group }}"
    mode: "0644"