---

## amazon in their stupidity cannot play nice with apt
- name: Download AWS CLI
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
- name: Unzip AWS CLI
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true
- name: Install AWS CLI
  command: /tmp/aws/install # --update
  args:
    creates: /usr/local/bin/aws

- name: Create .aws directory
  file:
    path: /root/.aws
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Install config
  template:
    src: root/_aws/config
    dest: "/root/.aws/config"
    owner: root
    group: root
    mode: "0644"

- name: copy aws credentials
  ansible.builtin.copy:
    src: "{{ lookup('env', 'PWD') }}/vars/_aws/credentials"
    dest: /root/.aws/credentials
    owner: root
    group: root
    mode: '0600'

