
---
- name: docker_repo
  ansible.builtin.git:
    repo: git@github.com:wasya-co/docker.git
    dest: /opt/projects/docker
    version: 'master'
    key_file: "{{ git_key_path }}"
    accept_hostkey: true
    update: yes

