
##
## currently unused
##

server {
  listen       443 ssl;
  server_name  {{ domain }} ;
  root /opt/projects/fedfis_backend3/current/public;

  passenger_enabled on;
  passenger_ruby /home/victor/.rbenv/versions/2.7.5/bin/ruby;
  passenger_sticky_sessions on;
  passenger_app_env staging;

  ssl_certificate /etc/letsencrypt/live/{{ domain }}/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}