
server {
  listen       443 ssl;
  server_name  {{ domain }} ;
  root /opt/projects/{{ project_slug }}/build;
  location / {
    try_files $uri /index.html;
  }
  ssl_certificate /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;

}
